# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataRow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 116)
        Form.setStyleSheet("QPushButton{\n"
"background-color:#16191d;\n"
"border-radius:15px;\n"
"padding: 10px;\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#2c313c;\n"
"}\n"
"#widget {\n"
"    border-radius: 10px;\n"
"    border: 5px solid white;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.showImage = QtWidgets.QPushButton(self.widget)
        self.showImage.setStyleSheet("")
        self.showImage.setObjectName("showImage")
        self.horizontalLayout_2.addWidget(self.showImage, 0, QtCore.Qt.AlignRight)
        self.editLabel = QtWidgets.QPushButton(self.widget)
        self.editLabel.setObjectName("editLabel")
        self.horizontalLayout_2.addWidget(self.editLabel, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "date"))
        self.label_2.setText(_translate("Form", "label"))
        self.showImage.setText(_translate("Form", "Show Image"))
        self.editLabel.setText(_translate("Form", "Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
